/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { WarmMinimalInventory } from 'dsh-warm-minimal/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7761726d4d696e696d616c {
    queryInventory: () => Promise<RemoteResult<WarmMinimalInventory>>
  }
  interface TypertRemoteMap {
    'warmMinimal/queryInventory': () => Promise<RemoteResult<WarmMinimalInventory>>
  }
  interface TypertRemoteNamespaceMap {
    'warmMinimal': TypertRemoteNamespace$7761726d4d696e696d616c
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
