/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_warm_minimal_warmMinimal_queryInventory_result$schema = z.object({
  'promptSources': z.array(z.object({
  'source': z.string().readonly(),
  'defaultAssignment': z.union([z.literal("parent-only"), z.literal("child-only"), z.literal("shared")]).readonly(),
  'sections': z.array(z.string()).readonly(),
  'contexts': z.array(z.string()).readonly(),
})).readonly(),
  'tools': z.array(z.object({
  'id': z.string().readonly(),
  'source': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'defaultAssignment': z.union([z.literal("parent-only"), z.literal("child-only"), z.literal("shared")]).readonly(),
})).readonly(),
})

export const TYPERT = {
  package: 'dsh-warm-minimal',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-warm-minimal#warmMinimal/queryInventory',
      service: 'warmMinimal',
      namespace: 'warmMinimal',
      method: 'queryInventory',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-warm-minimal/types#WarmMinimalInventory',
        schema: dsh_warm_minimal_warmMinimal_queryInventory_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-warm-minimal/src/remote.ts","line":28,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
